//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorRoleRequests
    {
        public int RequestId { get; set; }
        public int UserId { get; set; }
        public string Message { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedUtc { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
    }
}
