//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        public int ComplaintId { get; set; }
        public byte TargetKind { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> AuthorUserId { get; set; }
        public Nullable<int> ReviewId { get; set; }
        public int ComplainantUserId { get; set; }
        public string Description { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedUtc { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
        public virtual AppUsers AppUsers1 { get; set; }
        public virtual Books Books { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}
