//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FreezeDisputes
    {
        public int DisputeId { get; set; }
        public byte DisputeKind { get; set; }
        public Nullable<int> TargetBookId { get; set; }
        public Nullable<int> TargetReviewId { get; set; }
        public Nullable<int> TargetUserId { get; set; }
        public int RequesterUserId { get; set; }
        public string Message { get; set; }
        public byte Status { get; set; }
        public System.DateTime CreatedUtc { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
        public virtual AppUsers AppUsers1 { get; set; }
        public virtual Books Books { get; set; }
        public virtual Reviews Reviews { get; set; }
    }
}
