//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace libraryapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookShelves
    {
        public int UserId { get; set; }
        public int BookId { get; set; }
        public byte ShelfType { get; set; }
    
        public virtual AppUsers AppUsers { get; set; }
        public virtual Books Books { get; set; }
    }
}
